export const SET_NOW_PLAYING = 'SET_NOW_PLAYING'
export const SET_CURRENT_MOVIE = 'SET_CURRENT_MOVIE'
export const RESET_CURRENT_MOVIE = 'RESET_CURRENT_MOVIE'
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'
